services:
  nextjs:
    container_name: nextjs-web
    build:
      context: ./nextjs-web
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - D:/whiteborad/whiteboard-multiplayer/nextjs-web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - nextjs-web/.env.local
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/whiteboard"
      NEXTAUTH_URL: "https://gachaboar.uk"
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        npm install &&
        npx prisma generate &&
        npx prisma db push --url $$DATABASE_URL &&
        exec npm run dev -- --hostname 0.0.0.0 --port 3000
      "
  postgres:
    image: postgres:16
    container_name: whiteboard-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whiteboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -q"]
      interval: 2s
      timeout: 5s
      retries: 5

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: gachaboard-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: "eyJhIjoiMDllYTk5OTZlMjAzMjkxMWQ1OWQyYTg5YjEwZTA3NzgiLCJ0IjoiMzQzOTI5Y2ItZjZjYy00YWQ3LWJkYjMtZGJlMTgzYjViYmYwIiwicyI6Ik1UUXlNREl5TmpRdE9EWXlaQzAwTlROaUxXRXdNek10TnpVeU56UTFNR0UwTkRrMSJ9"
    depends_on:
      - nextjs

volumes:
  postgres_data:
