services:
  nextjs:
    container_name: nextjs-web
    build:
      context: ./nextjs-web
      dockerfile: Dockerfile
    working_dir: /app
    command: npm run dev -- --hostname 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    volumes:
      - D:/whiteborad/whiteboard-multiplayer/nextjs-web:/app
      - /app/node_modules
      - /app/.next
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
